#!/bin/bash
set -e

# Create a virtual environment in /usr/share/openlauncher/venv
VENV_DIR="/usr/share/openlauncher/venv"
if [ -d "$VENV_DIR" ]; then
    source "$VENV_DIR/bin/activate"
else
    python3 -m venv "$VENV_DIR"
    # Activate the virtual environment
    source "$VENV_DIR/bin/activate"
fi

# Ensure pip is installed
if ! command -v pip &> /dev/null; then
    echo "pip could not be found. Please install it to continue."
    exit 1
fi

# Install dependencies in the virtual environment
pip3 install minecraft_launcher_lib pypresence

# Deactivate the virtual environment
deactivate

echo "OpenLauncher has been installed successfully!"
